[general]
[colors.primary]
background = "#181616"
foreground = "#C5C9C5"

[colors.normal]
black   = "#181616"
red     = "#C4746E"
green   = "#8A9A7B"
yellow  = "#C4B28A"
blue    = "#7FB4CA"
magenta = "#938AA9"
cyan    = "#8EA4A2"
white   = "#C5C9C5"

[colors.bright]
black   = "#1F1F28"
red     = "#E46876"
green   = "#98BB6C"
yellow  = "#E6C384"
blue    = "#7E9CD8"
magenta = "#9CABCA"
cyan    = "#A3D4D5"
white   = "#DCD7BA"

[colors.cursor]
text = "#181616"
cursor = "#C5C9C5"

[colors.selection]
text = "#181616"
background = "#7E9CD8"

[window]
dynamic_padding = true
opacity = 0.95
blur = true

[font]
size = 12
normal = { family = "Terminess Nerd Font Mono", style = "Regular" }
